language: php
php:
    - 5.6
    - 5.5
    - 5.4
    - 5.3

env:
    - LIBZOOKEEPER_VERSION=3.5.2-alpha
    - LIBZOOKEEPER_VERSION=3.4.9

install:
    - sudo apt-get install -y lcov
    - gem install coveralls-lcov

before_script:
    - ./.travis/install_libzookeeper.sh $LIBZOOKEEPER_VERSION

script:
    - ./.travis/build.sh $LIBZOOKEEPER_VERSION

after_success:
    - coveralls-lcov coverage.info
