language: php
php:
    - 7.1
    - 7.0
    - 5.6
    - 5.5
    - 5.4
    - 5.3

env:
    - LIBZOOKEEPER_VERSION=3.5.2-alpha
    - LIBZOOKEEPER_VERSION=3.4.8

addons:
  apt:
    packages:
      - lcov

sudo: false

install:
    - gem install coveralls-lcov

before_script:
    - ./.travis/install_libzookeeper.sh $LIBZOOKEEPER_VERSION

script:
    - ./.travis/build.sh $LIBZOOKEEPER_VERSION

after_success:
    - coveralls-lcov coverage.info

